Feature/monitoring
synaptic-cl/SYNAPTIC-bot_monitor pull request #1
Opened 2021-07-01 22:59 UTC by TebanCL

|
|-- terraform: Deploy del admin y el monitor.
|-- monitor: El que se encarga de hacer la pega de revisar, avisar y loggear.
\_ monitor-admin: Escribe la config: entidades, acciones y credenciales.

2021-07-02 21:48 UTC, TebanCL commented
![imagen](https://user-images.githubusercontent.com/1278939/124331669-b16bb700-db5d-11eb-9753-24b78855f9cf.png)

2021-07-05 15:09 UTC, djuretic commented on monitor-admin/README.md
> +**Description:** Return the entitu with id = `entityId`.
```suggestion
**Description:** Return the entity with id = `entityId`.
```

2021-07-05 18:47 UTC, TebanCL commented
Update: Añade mensajes a Slack `#synaptic-bots-monitor`

2021-07-05 20:42 UTC, TebanCL commented
Update: Al desplegar la infraetructura ambos servicios se levantan no permitiendo la ejecución sin autenticación, esto provocaba que el scheduler fallara. Se agregó `oidcToken` utilizando la cuenta de servicio del monitor (el email se settea automaticamente desde terraform) para autenticar la llamada `Cloud Scheduler -> Cloud Run`

2021-07-06 02:55 UTC, hvillarroel requested changes
solo he visto el admin:

- [x] Solo se debe desactivar si da un 401
- [ ] username y password deberian estar dentro del objecto args el cual se cifra por completo y por completo se le pasa al bot https://api.openbanking.synaptic.cl/#operation/task-launch
- [ ] no he visto lo de slack pero podría hacer un `@` a algún team
- [ ] deja un pequeño swagger de la api o busquemos una solución clara para documentar los endpoint que estamos creando por servicio.

2021-07-06 02:55 UTC, hvillarroel commented on monitor-admin/README.md
> +          "usernameKey": "username",
el username y el password dejalo dentro de args, ya que quizas algun bot necesite un tercer o cuarto argumento o quizas 1.

2021-07-06 02:55 UTC, hvillarroel commented on monitor-admin/README.md
> +          "usernameKey": "username",
Ademas los endpoints no deberian exponer la password

2021-07-06 02:55 UTC, hvillarroel commented on monitor-admin/README.md
> +          "password": {
tampoco deberia retornar la password

2021-07-06 02:55 UTC, hvillarroel commented on monitor-admin/cloudbuild.yaml
> +          --memory '1500' \
esto no necesita tanta memoria ademas que puede tener muchas mas instancias en caso que lo necesitemos:

default memory (creo que son 512)
80 request concurrentes
10 instancias

2021-07-06 02:55 UTC, hvillarroel commented on monitor-admin/package.json
> +    "postpublish": "pinst --enable"
eso no es un paquete, no deberia tener esto

2021-07-06 02:55 UTC, hvillarroel commented on monitor-admin/package.json
> +    "nanoid": "^3.1.23"
para que usas esto?

2021-07-06 02:55 UTC, hvillarroel commented on monitor-admin/src/config.ts
> +const optionsNodeEnv = ['production', 'development', 'beta', 'test'];
Comentario para todo el archivo:

Es mejor que hagas fallar en caso de que no se haya definido alguna variable necesaria

2021-07-06 02:55 UTC, hvillarroel commented on monitor-admin/src/schema/entity.ts
> +  passwordKey: Joi.string(),
dejalo dentro de un objeto que se llame args como en la definición de la API https://api.openbanking.synaptic.cl/#operation/task-launch

2021-07-06 02:55 UTC, hvillarroel commented on monitor-admin/src/tools/kms.ts
> +    password: pass
no seria dejar cualquier cosa aqui, asi no te importa lo que sea tu siempre cifras todo lo que venga en el args y cuando lo decifras se lo pasas al bot

2021-07-06 02:55 UTC, hvillarroel commented on monitor-admin/src/server.ts
> +  return updateEntity(req, res);
el model deberia manejar el request?, creo que el modelo deberia manejar la logica y el router las respuesta en caso de exito o falla

2021-07-06 02:55 UTC, hvillarroel commented on monitor-admin/src/tools/scheduler.ts
> +        serviceAccountEmail: MONITOR_INVOKER_EMAIL
usa un nombre un poco mas descriptivo como `GCLOUD_SERVICE_ACCOUNT_OIDC`, así lo tenemos en el controller-manager cuando encolamos una tarea al tasks

2021-07-06 02:55 UTC, hvillarroel commented on monitor-admin/src/tools/scheduler.ts
> +export const deletePreviousJob = async (entityName: string, actionName: string): Promise<void> => {
no me queda tan claro en que caso usas esta funcion

2021-07-06 02:55 UTC, hvillarroel commented on monitor-admin/src/types/index.d.ts
> +  passwordKey?: string;
lo mismo del args

2021-07-06 15:07 UTC, TebanCL commented on monitor-admin/src/tools/scheduler.ts
> +        serviceAccountEmail: MONITOR_INVOKER_EMAIL
Dale, pensaba que era lo suficientemente descriptivo jajaja, lo dejé como lo propusiste e hice el cambio en el terraform, esa variable se rellena sola, asi que no habría problema en que nos confundamos con eso en algun momento.

2021-07-06 15:08 UTC, TebanCL commented on monitor-admin/package.json
> +    "nanoid": "^3.1.23"
era para darle un id a los registros en firetore, me habia gustado como le quedo eso al felipe en el backend del front

2021-07-06 15:09 UTC, TebanCL commented on monitor-admin/package.json
> +    "postpublish": "pinst --enable"
eso pasa por copypastear :D
en verdad necesitaba los de dev, test, format y lint y no quise escribirlos, asi que copie nomas

2021-07-06 15:10 UTC, TebanCL commented on monitor-admin/cloudbuild.yaml
> +          --memory '1500' \
Te cacho, me base en el cloudbuild de los bots y no le cambié la memoria, ni la mire

2021-07-06 15:14 UTC, hvillarroel commented on monitor-admin/package.json
> +    "nanoid": "^3.1.23"
oka

2021-07-06 15:17 UTC, TebanCL commented on monitor-admin/src/tools/scheduler.ts
> +export const deletePreviousJob = async (entityName: string, actionName: string): Promise<void> => {
tuve problemas haciendo la actualización (de hecho esta la funcion ahi, pero deje de usarla), me pasaba derrepente que se duplicaban las tareas en vez de modificarse (no cache que onda, de hecho no deberia porque uno le pasa el name que es la ruta completa del job), asi que opté por eliminar el job existente en caso de modificaciones e hiciera uno nuevo. La ejecución se va al logging y está la notificación del slack, asi que no es que se vaya a perder información

2021-07-06 15:25 UTC, TebanCL commented
> solo he visto el admin:
> 
>     * [ ]  Solo se debe desactivar si da un 401
Eso no lo concideré, pero cierto podría hacer eso para evitar que lo bloquee. El desactivar igual creo que debiese estar para hacer la actualización manual (sobretodo al estar probando) 🤔 


>     * [ ]  username y password deberian estar dentro del objecto args el cual se cifra por completo y por completo se le pasa al bot https://api.openbanking.synaptic.cl/#operation/task-launch

Basicamente sería agarrar ese objeto credenciales y encriptar lo que sea que venga sin preocuparme de que key viene (aunque igual tenga ese mismo schema `user?, pass?`. Se te ocurre alguna propuesta del json con el que se crearía/actualizaría? como que le doy vueltas y llego a lo mismo que tengo, una lista de acciones con un obj credentials 🤔 

>     * [ ]  no he visto lo de slack pero podría hacer un `@` a algún team

// TO DO 

>     * [ ]  deja un pequeño swagger de la api o busquemos una solución clara para documentar los endpoint que estamos creando por servicio.

Quizas un api gateway para todo y que quede documentado ahi?

2021-07-07 01:50 UTC, hvillarroel requested changes

2021-07-07 01:50 UTC, hvillarroel commented on monitor/cloudbuild.yaml
> +          --max-instances '1' \
dejalo e 10

2021-07-07 01:50 UTC, hvillarroel commented on monitor/package.json
> +    "pinst": "^2.1.4",
esto no se usa

2021-07-07 01:50 UTC, hvillarroel commented on monitor/src/check.ts
> +  if (!action) return monitorError(500, Status.ERROR, 'Couldn`t retrieve action.');
a veces el body responde mensajes en el error, deberías guardar eso

2021-07-07 01:50 UTC, hvillarroel commented on monitor/src/check.ts
> +  if (!username) return monitorError(404, Status.ERROR, 'Couldn`t retrieve credentials.');
aqui tambien

2021-07-07 01:50 UTC, hvillarroel commented on monitor/src/config.ts
> +}
y si mejor haces esto:

```ts
export const KMS_KEY_RING = process.env.KMS_KEY_RING || throwErr('Please set the KMS_KEY_RING variable');
```

Lo usamos en el config del controller-manager

2021-07-07 01:50 UTC, hvillarroel commented on monitor/src/server.ts
> +  const { entityId, actionType } = req.body;
que pasa cuando `entityId` y/o `actionType` no están registradas?

2021-07-07 01:50 UTC, hvillarroel commented on monitor/src/server.ts
> +  const response = await check(entityId, actionType);
veo que le devuelves la respuesta, esta es la del servicio de bot?, en ese caso no deberia ser asi ya que este servicio deberia manejar sus propios errores que son distintos al del servicio.

Un ejemplo, si el monitoreo hizo todo bien es un 200 pero el servicio de bot está malo entonces el cuerpo de la respuesta te lo tiene que decir o en este caso lo guarda como un error y noticias.

2021-07-07 01:50 UTC, hvillarroel commented on monitor/src/tools/kms.ts
> +};
después de lo que hablamos hoy creo que eso seria mas una función de proxy y no tendria logica.

2021-07-07 01:50 UTC, hvillarroel commented on monitor/src/tools/task.ts
> +  return client
esto debería quedar mas genérico según lo que hablamos hoy

2021-07-07 01:50 UTC, hvillarroel commented on terraform/README.md
> +```
podrías dejarlo algo asi https://github.com/synaptic-cl/SYNAPTIC-bot_terraform/tree/feature/refactor_cloud_run

2021-07-07 01:50 UTC, hvillarroel commented on terraform/environments/dev/module.tf
> +  GATEWAY_ENVIRONMENT = var.GATEWAY_ENVIRONMENT
qué responsabilidad cumple esta variable?

2021-07-07 01:50 UTC, hvillarroel commented on terraform/modules/main/06_scheduler.tf
> +# }
si no lo vas a ocupar eliminalo mejor

2021-07-07 21:09 UTC, TebanCL commented on monitor-admin/README.md
> +          "usernameKey": "username",
Esto quedo dentro del `args`, ahora el args completo se cifra y eso queda guardado. Al preguntar por un entity devuelve un args como `"Not Shown"` (en verdad solo para que no me alegara el ts porque el args debe ir)

2021-07-07 21:09 UTC, TebanCL commented on monitor-admin/README.md
> +          "password": {
👌🏼

2021-07-07 21:09 UTC, TebanCL commented on monitor-admin/src/tools/kms.ts
> +    password: pass
Esto quedo cifrado ya

2021-07-07 21:10 UTC, TebanCL commented on monitor-admin/src/server.ts
> +  return updateEntity(req, res);
Hice un cambio con respecto a eso, dale una mirada para saber si es lo que pensabas 😉

2021-07-07 21:10 UTC, TebanCL commented on monitor-admin/src/types/index.d.ts
> +  passwordKey?: string;
hecho 😉

2021-07-07 21:10 UTC, TebanCL commented on monitor/cloudbuild.yaml
> +          --max-instances '1' \
dale, quedo con instances 10

2021-07-07 21:10 UTC, TebanCL commented on monitor/package.json
> +    "pinst": "^2.1.4",
cierto, tambien estaba en el admin, lo quite

2021-07-07 21:11 UTC, TebanCL commented on monitor/src/config.ts
> +}
hecho 😉

2021-07-07 21:12 UTC, TebanCL commented on monitor/src/tools/kms.ts
> +};
hecho 😉

2021-07-07 21:12 UTC, TebanCL commented on monitor/src/tools/task.ts
> +  return client
hecho

2021-07-07 21:12 UTC, TebanCL commented on terraform/README.md
> +```
hehco

2021-07-07 21:13 UTC, TebanCL commented on terraform/environments/dev/module.tf
> +  GATEWAY_ENVIRONMENT = var.GATEWAY_ENVIRONMENT
Eso es solo para QoL, para mostrar en los errores en que env esta el ambiente en el q se esta monitoreando, si no esta no lo usa nomas

2021-07-07 21:13 UTC, TebanCL commented on terraform/modules/main/06_scheduler.tf
> +# }
done

2021-07-07 21:28 UTC, TebanCL commented on monitor/src/server.ts
> +  const { entityId, actionType } = req.body;
Si lo tiras manualmente te va a tirar un error de que no pudo obtener la entidad o acción.
El scheduler se crea automáticamente, pero si eliminaramos a la mala desde firestore la entidad o la desactivaramos le devolvería un error de que esta desactivada o inactiva (y nos avisaria por slack)

2021-07-09 16:42 UTC, TebanCL commented on monitor-admin/src/schema/entity.ts
> +  passwordKey: Joi.string(),
👌🏼

2021-07-09 16:44 UTC, TebanCL commented on monitor/src/server.ts
> +  const response = await check(entityId, actionType);
Esto lo conversamos hoy, por ahora lo dejamos asi y buscamos como mejorarlo luego. Por ahora lo que si agregué que no estaba considerado era avisar cuando el monitor moria (hoy paso, pero no cache por qué), ahora tengo eso capturado y logeo cuando muere.

2021-07-09 16:44 UTC, TebanCL commented on monitor/src/check.ts
> +  if (!action) return monitorError(500, Status.ERROR, 'Couldn`t retrieve action.');
Aca probe y no encontré ese mensaje que me decias, tienes algun ejemplo?

2021-07-09 16:44 UTC, TebanCL commented on monitor/src/check.ts
> +  if (!username) return monitorError(404, Status.ERROR, 'Couldn`t retrieve credentials.');
Aca probe y no encontré ese mensaje que me decias, tienes algun ejemplo?

2021-07-12 14:55 UTC, hvillarroel commented on monitor-admin/src/server.ts
> +    return res.status(500).send({ data: [], message: error.message });
yo le diria que hubo un error, si no estas capturando el error por tipo entonces creo que es mejor que no lo devuelvas en el response

2021-07-12 14:55 UTC, hvillarroel commented on monitor-admin/src/server.ts
> +    return res.status(500).send({ data: [], message: error.message });
Lo mismo de devolver el error

2021-07-12 14:55 UTC, hvillarroel commented on monitor/src/check.ts
> +  if (!action) return monitorError(500, Status.ERROR, 'Couldn`t retrieve action.');
eso pasa en cierto errores, como cuando el formato de la contraseña es incorrecto

2021-07-12 14:56 UTC, hvillarroel commented on monitor/src/check.ts
> +  if (!action) return monitorError(500, Status.ERROR, 'Couldn`t retrieve action.');
otra cosa, cambia `'Couldn`t retrieve action.'` por `"Couldn't retrieve action."`

2021-07-12 15:38 UTC, TebanCL commented on monitor-admin/src/server.ts
> +    return res.status(500).send({ data: [], message: error.message });
Dale, era maña nomas que lo dejé

2021-07-12 15:39 UTC, TebanCL commented on monitor-admin/src/server.ts
> +    return res.status(500).send({ data: [], message: error.message });
Dale, era maña nomas que lo dejé

2021-07-12 17:39 UTC, TebanCL commented
@hvillarroel 
<img width="913" alt="imagen" src="https://user-images.githubusercontent.com/1278939/125331151-99dabe00-e315-11eb-9d5c-619083ee4453.png">

No me dejaba responder arriba, te respondo aca:

uta ahi en esa parte hay 3 errores:

1. `Couldn't get a Session Token.
Aca hubo un error onda con la api key (invalida o no esta puesta en el secret manager) o un error en el auth que no devolvio el token.
2. 'Couldn`t retrieve action.')
Aca puede ser que o no encontro la entity o no encontro la accion o alguna de esas esta desactivada.
3. 'Couldn`t retrieve credentials.'
Seria un error en el kms o se metio mano a la info en firestore y no puede desencriptarla
4. Al momento de postear la tarea pueden pasar hartas cosas: 
Onda el args no esta bien definido y te lo devuelve (onda sin username) o hubo algun problema al postear al launcher, aca el error que se devuelve debiese ser textual el del launcher (cache que no siempre lo hace, asi que voy a arreglar eso)

Quizas en 1,2 y 3 debiese ser mas explicito con que pudo haber fallado como lo que te escribí arriba para que otro que no sea yo sepa leer bien el error

2021-07-21 19:59 UTC, merged