Feature/v2.0.0
synaptic-cl/SYNAPTIC-bot_monitor pull request #6
Opened 2021-07-27 21:13 UTC by TebanCL

Cuando agregué el tema del `traceId` me compliqué entero y terminé dándome cuenta que estaba mal armado el monitor, tenia muchos puntos de salida iguales para lo mismo (los errores) y tenía una ensalada de tipos muy grande, así que preferí cortar por lo sano y echármelo casi todo, quedo estructurado como un flujo y un único manejador del error.

Tengo una duda ahora (y lo conversamos con el Héctor hace unos días), debería retornar al tiro y dejar el monitor corriendo y que avise si sale un error o debería esperar a que me responda el resultado del flujo antes de retornar?

La diferencia es mantener o quitar el `await` de la línea `./monitor/src/server.ts:32`. Si lo mantengo el resultado (de cara al Scheduler) será el mismo del resultado de cada prueba (Marcara cuando corresponda `success` o `failed`), si lo quito el monitor el Scheduler dira siempre `success` aun cuando la prueba haya tirado un error (pero ese error se notifica al slack igual).

TO DO: Quedo mucho mas fácil el testear, así que tocaría testear esto.

2021-07-29 19:02 UTC, hvillarroel commented on monitor/package.json
> +  "version": "2.0.0",
que rapido el paso de `0.1.0` a `2.0.0`

2021-07-29 19:13 UTC, hvillarroel requested changes

2021-07-29 19:13 UTC, hvillarroel commented on monitor/src/flow/handleAPIKey.ts
> +    projectId: PROJECT_ID || '',
no deberia estar vacio, mejor implementa la funciona que te da un error si no esta definido @djuretic te puede decir donde se usó.

2021-07-29 20:03 UTC, FelipeRubilar commented on monitor/src/flow/handleAPIKey.ts
> +    projectId: PROJECT_ID || '',
lo usé en el entities: https://github.com/synaptic-cl/SYNAPTIC-bot_entities/blob/main/src/config.ts

2021-07-29 20:08 UTC, TebanCL commented on monitor/package.json
> +  "version": "2.0.0",
Si, culpa mia, deje el 0.1.0 en la primera versión que hice y cuando pasé la versión anterior no le hice el bump, me acorde de eso recien ayer

2021-07-29 20:08 UTC, TebanCL commented on monitor/src/flow/handleAPIKey.ts
> +    projectId: PROJECT_ID || '',
de hecho eso esta, ese `|| ''` está de más, voy a quitarlo

2021-07-30 14:29 UTC, djuretic commented on monitor/src/flow/index.ts
> +    .then((response) => handleAction(response))
```suggestion
    .then(handleAction)
```
Ídem para las funciones de abajo que sólo reciben response como parámetro

2021-07-30 14:49 UTC, djuretic commented on monitor/src/types/index.ts
> +export interface ErrorCatched {
Me suena mejor `CaughtError`, qué opinas @FelipeRubilar ?

2021-07-30 16:08 UTC, TebanCL commented on monitor/src/flow/index.ts
> +    .then((response) => handleAction(response))
done

2021-07-30 16:10 UTC, FelipeRubilar requested changes

2021-07-30 16:10 UTC, FelipeRubilar commented on monitor/src/flow/handleResult.ts
> +};
Esto igual lo movería a un `taskService`, como para mantener consistencia e indicar también que estás consultando a algo externo

2021-07-30 16:10 UTC, FelipeRubilar commented on monitor/src/flow/handleSessionToken.ts
> +    });
Mover a un `loginService` y después acá haces un
```ts
return LoginService.login(apiKey)
```

o algo por el estilo

2021-07-30 16:10 UTC, FelipeRubilar commented on monitor/src/flow/handleTask.ts
> +    });
Mover al `taskService` y después hacer
```ts
return TaskService.createTask(...)
```

o algo similar

2021-07-30 16:13 UTC, djuretic commented on monitor/src/flow/handleAction.ts
> +    return Promise.reject({ message: `Entity "${entityId}" does't exits.`, status: 404, step });
Buena idea, queda más ordenado

2021-09-24 16:47 UTC, merged